---
title: "Mapping Examples"
author: "Geoffrey Arnold"
date: "12/23/2020"
output: html_document
---


```{r setup, include=FALSE}
require(sf)
require(leaflet)
require(leaflet.extras)
require(ggplot2)
require(ggmap)
require(ggthemes)
require(dplyr)
require(readxl)
require(stringr)
```
# Spatial Data
## Getting Spatial Data

```{r, loading}
cds.load <- st_read("./cb_2015_us_cd114_500k/cb_2015_us_cd114_500k.shp")
plot(cds.load)

polls <- st_read("Allegheny_County_Polling_Place_Locations_November_2016.geojson")
```

## Basic Plot
```{r, plot}
plot(cds.load)
```


## Merging Table Data to your shapefile

```{r, merging}
op_data <- read_excel("Geographies_of_Opportunity_Ranking_Well_Being_by_Congressional_District_(114th_Congress).xlsx") %>%
  mutate(Number = str_pad(Number, 4, pad = "0"))

# Merge with Left Join
cds <- cds.load %>%
  left_join(op_data, by = c("GEOID" = "Number"))
```

## ggplot polygon

```{r ggplot_poly}
ggplot(data=cds, aes(fill = `Graduate Degree (%)`)) + 
  geom_sf() +
  theme_void()
```

## ggplot points
```{r ggplot_points}
ggplot(data=polls, aes(color = Region)) + 
  geom_sf() +
  theme_void()
```

## ggmap

```{r ggplot_map}
# Get the boundaries of your file to get the basemap
bbox <-st_bbox(polls) %>% setNames(c("left", "bottom", "right", "top"))

# Get the API Key
ggmap::register_stadiamaps(Sys.getenv("GGMAP_STADIAMAPS_API_KEY"))

# Load API Basemap
map <- get_stadiamap(bbox, maptype = "stamen_toner_lite")

# Add map info to basemap
map %>% 
	ggmap() +   
	coord_sf(crs = st_crs(3857)) +  
	geom_sf(data=polls, aes(color = Region), inherit.aes = FALSE) +  
	theme_map()
```

# Leaflet
## Blank map with basemap

```{r}
leaflet() %>%
  addProviderTiles(providers$Esri.WorldImagery)
```

## Blank map with no wrap

```{r}
leaflet() %>%
  addProviderTiles(providers$Esri.WorldImagery, options = providerTileOptions(noWrap = TRUE))
```

## Shape

```{r, polygon}

```

# Lines

```{r, lines}
rivers <- st_read("./ne_10m_rivers_lake_centerlines")

leaflet(data = rivers) %>%
  addProviderTiles("Esri.WorldTerrain", options = providerTileOptions(noWrap = TRUE)) %>%
  addPolylines(color = "#63CBD3")
```

## Line with Popups

```{r, popups}
leaflet(data = rivers) %>%
  addProviderTiles("Esri.WorldTerrain", options = providerTileOptions(noWrap = TRUE)) %>%
  addPolylines(color = "#63CBD3", popup = ~name_en)
```

## Points

### Circle Markers

```{r, markers}
potholes <- read.csv("311_potholes.csv")

# Custom Palette
pal311 <- colorFactor(c("#d73027", "#1a9850"), c("Closed", "Open"))

leaflet() %>%
  addProviderTiles("OpenStreetMap.HOT") %>%
  addCircleMarkers(data = potholes, lng = ~X, lat = ~Y, radius = 1.5, color = ~pal311(STATUS)) %>%
  addLegend(position = "topright" , pal = pal311, values = potholes$STATUS, title = "Status")
```

### Points from GEOJSON

```{r, geojson}
leaflet(data = polls) %>%
  addProviderTiles("OpenStreetMap.Mapnik") %>%
  addMarkers(popup = ~paste0(LocName, ": ", NewAddress, " ", City, " PA ", Zip))
```

### Points Awesome Markers

```{r, awesome_markers}
potOver <- read.csv("potholesOvergrowth.csv")

icons <- awesomeIconList(
  Potholes = makeAwesomeIcon(icon = "road", library = "fa", markerColor = "gray"),
  Overgrowth = makeAwesomeIcon(icon = "leaf", library = "fa", markerColor = "green")
)

leaflet(data = potOver) %>%
  addProviderTiles("OpenStreetMap.HOT") %>%
  addAwesomeMarkers(lng = ~X, lat = ~Y, icon = ~icons[REQUEST_TYPE], popup = ~REQUEST_TYPE)
```
